const TechStackContent = {
	languages: ["Typescript", "Javascript", "Python", "HTML", "CSS"],
	frontend: [
		"React.js",
		"Next.js",
		"Angular",
		"React Native",
		"Redux",
		"Redux Toolkit",
		"Redux Thunk",
		"ContextAPI",
		"Graphql",
		"Ant Design",
		"Material UI",
		"Tailwind.css",
		"ThirdWeb",
		"Charts.js",
		"socket.io",
		"Styled-components",
		"Video.js",
		"Video JS Record",
		"Mapbox",
		"Openstreet Maps",
		"Nextra",
		"SCSS",
		"LESS",
		"CSS",
	],
	backend: [
		"Node.js",
		"Express.js",
		"Nest.js",
		"Python Flask",
		"SQL-alchemy",
		"TypeORM",
		"Prisma",
		"Mongoose",
		"Hasura",
		"Strapi",
		"OWASP",
		"JWT (JSON Web Tokens)",
	],
	database: ["MongoDB", "Postgres", "SQLite", "rxDB"],
	testing: ["Cypress", "Jest", "Enzyme", "SonarQube"],
	"Version Control": ["Git", "Bitbucket", "GitHub"],
	"CI/CD": ["GitHub Actions", "Bitbucket Pipelines"],
	"Cloud Services": [
		"AWS S3",
		"AWS Lambda",
		"AWS EC2",
		"AWS SES",
		"AWS ECS",
		"AWS RDS",
		"Heroku",
		"Digital Ocean",
	],
	Integrations: ["Stripe", "Agora", "Twilio", "Pusher", "ChatGPT"],
	"Work Environment": ["Agile Scrum", "Jira", "Trello"],
};

export default TechStackContent;
